### ISSUE TITLE
Importing certificates without modules creates issues

### ISSUE THREAD

**Issue by Fede2782** [TheParasiteProject/vendor_google_mainline_modules#2]
Importing the networkstack.x509.pem without importing the network stack apk makes WiFi and internet not working. 

The same happens when importing Bluetooth.x509.pem without importing Bluetooth apex and this time makes Bluetooth not working 

There should be proper logic to address this.

**Comment by someone5678** [comment]
Thanks for the issue!

Those imported pem key directly compiled into sepolicy to allow only cert matching APEX installed and works.
So, to make AOSP apex works, we need to import AOSP pem keys over google pem keys.

Since current AOSP build system doesn't allow partial import of APEX pem keys, we always need to import all APEX pem keys which stated in system/sepolicy (bluetooth, network, etc.)

I'll try to fix that by allowing per-APEX pem key import!

**Comment by Fede2782** [comment]
@someone5678 make sure you guard also cellbroadcast cause it requires Google network stack otherwise it will make bootloop when updated cause StagedInstallManager will fail to install CellBroadcastService and will end in infinite rollback and reboot

**Comment by someone5678** [comment]
> @someone5678 make sure you guard also cellbroadcast cause it requires Google network stack otherwise it will make bootloop when updated cause StagedInstallManager will fail to install CellBroadcastService and will end in infinite rollback and reboot

I updated makefile and cert select logic. I want to test, but since my testing device is not working (not because of this changes. It's just broken even without mainline modules) I can't test these commits properly... If you have testing device and can test, please report back after applying this changes. It'll really helpful to me!!

**Comment by Fede2782** [comment]
> > @someone5678 make sure you guard also cellbroadcast cause it requires Google network stack otherwise it will make bootloop when updated cause StagedInstallManager will fail to install CellBroadcastService and will end in infinite rollback and reboot
> 
> I updated makefile and cert select logic. I want to test, but since my testing device is not working (not because of this changes. It's just broken even without mainline modules) I can't test these commits properly... If you have testing device and can test, please report back after applying these changes. It'll really helpful to me!!

I will surely test as soon as I fix the screen of my Moto G7. Unfortunately it has a legacy kernel so I cannot test all the modules like tethering on it and due to the small partition sized I can only use LineageOS which has severe issues when building with this repo inline and obliges me to do more manual testing. Moreover I am currently a bit busy with university exams these months. 

I did all the tests a few months ago that's also when I made the commits and discovered these issues.

**Comment by someone5678** [comment]
Checked with other device (Redmi K60). I can confirm the changes are working (auto cert selecting, etc.)
If you have any other issue, or related this issue, please re-open issue or create new. Thanks!!
